# Generated by Django 2.2.16 on 2022-04-30 19:37

from django.db import migrations, models
import django.db.models.deletion
import titles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Категория, к которой относится произведение', max_length=200, verbose_name='category name')),
                ('slug', models.SlugField(help_text='Уникальный URL категории', unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Жанр, к которому относится произведение', max_length=200, verbose_name='genre name')),
                ('slug', models.SlugField(help_text='Уникальный URL жанра', unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название произведения', max_length=200, verbose_name='title name')),
                ('year', models.IntegerField(blank=True, help_text='Год создания произведения', null=True, validators=[titles.validators.validator_year], verbose_name='year creation')),
                ('description', models.CharField(blank=True, help_text='Описание произведения', max_length=200, null=True, verbose_name='description')),
                ('category', models.ForeignKey(blank=True, help_text='Категория к которой относится произведение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='titles.Category', verbose_name='category')),
                ('genre', models.ManyToManyField(help_text='Жанр которой относится произведение', related_name='titles', to='titles.Genre', verbose_name='genre')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Genre')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Title')),
            ],
        ),
    ]
